services:
  cloakbrowser:
    image: cloakhq/cloakbrowser
    container_name: cloak-browser
    command: >
      cloakserve
      --proxy-server=socks5://sp80vsisy4:mu4i8+2RwdYe5pgTKn@gate.decodo.com:7000
    restart: unless-stopped
    ports:
      - "127.0.0.1:9222:9222"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9222/json/version"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s