# syntax=docker/dockerfile:1

# Stage 1: Base image.
FROM node:lts AS base
ENV FORCE_COLOR=0
RUN corepack enable
WORKDIR /opt/docusaurus

# Stage 2a: Development mode.
FROM base AS dev
WORKDIR /opt/docusaurus
EXPOSE 9009
CMD [ -d "node_modules" ] && npm run start -- --host 0.0.0.0 --poll 1000 -- -p 9009 || npm install && npm run start -- --host 0.0.0.0 --poll 1000 -- -p 9009

# Stage 2b: Production build mode.
FROM base AS prod
WORKDIR /opt/docusaurus
COPY docs/package*.json ./
COPY docs/.docusaurus ./.docusaurus
COPY docs/src ./src
COPY docs/docusaurus.config.ts .
COPY docs/sidebars.ts .
COPY docs/static ./static
COPY docs/blog ./blog
COPY docs/docs ./docs
COPY docs/Caddyfile .
RUN npm ci && npm run build

# Stage 3a: Serve with `docusaurus serve`.
FROM prod AS serve
EXPOSE 9009
CMD ["npm", "run", "serve", "--", "--host", "0.0.0.0", "--no-open", "-p", "9009"]

# Stage 3b: Serve with Caddy.
FROM caddy:2-alpine AS caddy
COPY --from=prod /opt/docusaurus/Caddyfile /etc/caddy/Caddyfile
COPY --from=prod /opt/docusaurus/build /var/docusaurus
