// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns service health status including available renderers, running browser instances, and active crawl job count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/crawl": {
            "post": {
                "description": "Start an async BFS crawl of a website. Returns immediately with a job ID for tracking progress via GET /v1/crawl/:id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crawling"
                ],
                "summary": "Start an async BFS crawl",
                "parameters": [
                    {
                        "description": "Crawl request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.CrawlRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.CrawlStartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/crawl/{id}": {
            "get": {
                "description": "Check the current status and results of a crawl job by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crawling"
                ],
                "summary": "Get crawl job status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Crawl job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.CrawlState"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Cancel a running crawl job by its ID",
                "tags": [
                    "crawling"
                ],
                "summary": "Cancel a crawl job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Crawl job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/map": {
            "post": {
                "description": "Discover all URLs on a website without scraping content. Uses BFS traversal and optionally sitemap.xml",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mapping"
                ],
                "summary": "Discover URLs on a website",
                "parameters": [
                    {
                        "description": "Map request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.MapRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.MapResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/scrape": {
            "post": {
                "description": "Scrape a single URL with one or more output formats. Supports HTTP/browser rendering, content filters, and LLM-based structured extraction.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scraping"
                ],
                "summary": "Scrape a single URL",
                "parameters": [
                    {
                        "description": "Scrape request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.ScrapeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/search": {
            "post": {
                "description": "Query SearXNG and return search results. Optionally scrape each result URL for content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search the web",
                "parameters": [
                    {
                        "description": "Search request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.SearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_MabudAlam_quickcrawl_internal_types.CrawlRequest": {
            "type": "object",
            "properties": {
                "formats": {
                    "description": "Desired output formats",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.OutputFormat"
                    }
                },
                "maxDepth": {
                    "description": "Maximum link depth",
                    "type": "integer"
                },
                "maxPages": {
                    "description": "Maximum pages to crawl",
                    "type": "integer"
                },
                "renderMode": {
                    "description": "Per-request override: \"auto\" | \"browser\" | \"http\". nil = inherit server default.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.RenderMode"
                        }
                    ]
                },
                "url": {
                    "description": "Starting URL",
                    "type": "string"
                },
                "waitFor": {
                    "description": "Wait time in ms",
                    "type": "integer"
                }
            }
        },
        "github_com_MabudAlam_quickcrawl_internal_types.CrawlStartResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Unique job ID for status checks",
                    "type": "string"
                },
                "success": {
                    "description": "Always true if job started",
                    "type": "boolean"
                }
            }
        },
        "github_com_MabudAlam_quickcrawl_internal_types.CrawlState": {
            "type": "object",
            "properties": {
                "completed": {
                    "description": "Pages successfully scraped",
                    "type": "integer"
                },
                "data": {
                    "description": "Scraped page data",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.ScrapeData"
                    }
                },
                "error": {
                    "description": "Error message if failed",
                    "type": "string"
                },
                "id": {
                    "description": "Unique job ID",
                    "type": "string"
                },
                "status": {
                    "description": "Current status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.CrawlStatus"
                        }
                    ]
                },
                "success": {
                    "description": "Whether job succeeded",
                    "type": "boolean"
                },
                "total": {
                    "description": "Total URLs discovered",
                    "type": "integer"
                }
            }
        },
        "github_com_MabudAlam_quickcrawl_internal_types.CrawlStatus": {
            "type": "string",
            "enum": [
                "scraping",
                "completed",
                "failed"
            ],
            "x-enum-comments": {
                "CrawlStatusCompleted": "Successfully completed",
                "CrawlStatusFailed": "Failed with error",
                "CrawlStatusInProgress": "Currently scraping"
            },
            "x-enum-descriptions": [
                "Currently scraping",
                "Successfully completed",
                "Failed with error"
            ],
            "x-enum-varnames": [
                "CrawlStatusInProgress",
                "CrawlStatusCompleted",
                "CrawlStatusFailed"
            ]
        },
        "github_com_MabudAlam_quickcrawl_internal_types.ExtractOptions": {
            "type": "object",
            "properties": {
                "prompt": {
                    "description": "Custom extraction prompt",
                    "type": "string"
                },
                "responseFormat": {
                    "description": "Custom response format name",
                    "type": "string"
                },
                "schema": {
                    "description": "JSON schema for structured extraction",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "github_com_MabudAlam_quickcrawl_internal_types.MapData": {
            "type": "object",
            "properties": {
                "links": {
                    "description": "Discovered URLs",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_MabudAlam_quickcrawl_internal_types.MapRequest": {
            "type": "object",
            "properties": {
                "maxDepth": {
                    "description": "Maximum link depth",
                    "type": "integer"
                },
                "timeout": {
                    "description": "Timeout in milliseconds",
                    "type": "integer"
                },
                "url": {
                    "description": "Starting URL",
                    "type": "string"
                },
                "useSitemap": {
                    "description": "Whether to check sitemap",
                    "type": "boolean"
                }
            }
        },
        "github_com_MabudAlam_quickcrawl_internal_types.MapResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Discovered URLs",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.MapData"
                        }
                    ]
                },
                "error": {
                    "description": "Error message",
                    "type": "string"
                },
                "success": {
                    "description": "Whether operation succeeded",
                    "type": "boolean"
                }
            }
        },
        "github_com_MabudAlam_quickcrawl_internal_types.OutputFormat": {
            "type": "string",
            "enum": [
                "markdown",
                "html",
                "rawHtml",
                "plainText",
                "links",
                "json",
                "imageLinks"
            ],
            "x-enum-comments": {
                "FormatHtml": "Clean HTML format",
                "FormatImageLinks": "All image src URLs",
                "FormatJson": "JSON (LLM extracted)",
                "FormatLinks": "Just the links found on page",
                "FormatMarkdown": "Markdown format (images stripped by default)",
                "FormatPlainText": "Plain text without markup",
                "FormatRawHtml": "Raw HTML as received"
            },
            "x-enum-descriptions": [
                "Markdown format (images stripped by default)",
                "Clean HTML format",
                "Raw HTML as received",
                "Plain text without markup",
                "Just the links found on page",
                "JSON (LLM extracted)",
                "All image src URLs"
            ],
            "x-enum-varnames": [
                "FormatMarkdown",
                "FormatHtml",
                "FormatRawHtml",
                "FormatPlainText",
                "FormatLinks",
                "FormatJson",
                "FormatImageLinks"
            ]
        },
        "github_com_MabudAlam_quickcrawl_internal_types.PageMetadata": {
            "type": "object",
            "properties": {
                "canonicalUrl": {
                    "description": "Canonical URL",
                    "type": "string"
                },
                "description": {
                    "description": "Meta description",
                    "type": "string"
                },
                "language": {
                    "description": "Page language",
                    "type": "string"
                },
                "ogpDescription": {
                    "description": "Open Graph description",
                    "type": "string"
                },
                "ogpImage": {
                    "description": "Open Graph image URL",
                    "type": "string"
                },
                "ogpTitle": {
                    "description": "Open Graph title",
                    "type": "string"
                },
                "renderedMode": {
                    "description": "How it was rendered (http/js)",
                    "type": "string"
                },
                "sourceURL": {
                    "description": "Actual URL scraped",
                    "type": "string"
                },
                "statusCode": {
                    "description": "HTTP status code",
                    "type": "integer"
                },
                "title": {
                    "description": "Page title",
                    "type": "string"
                }
            }
        },
        "github_com_MabudAlam_quickcrawl_internal_types.RenderMode": {
            "type": "string",
            "enum": [
                "auto",
                "browser",
                "http"
            ],
            "x-enum-varnames": [
                "RenderModeAuto",
                "RenderModeBrowser",
                "RenderModeHTTP"
            ]
        },
        "github_com_MabudAlam_quickcrawl_internal_types.ScrapeData": {
            "type": "object",
            "properties": {
                "html": {
                    "description": "Clean HTML",
                    "type": "string"
                },
                "imageLinks": {
                    "description": "Image URLs found on page",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "json": {
                    "description": "LLM extracted JSON",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "links": {
                    "description": "URLs found on page",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "markdown": {
                    "description": "Markdown conversion (images stripped)",
                    "type": "string"
                },
                "metadata": {
                    "description": "Page metadata",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.PageMetadata"
                        }
                    ]
                },
                "plainText": {
                    "description": "Plain text",
                    "type": "string"
                },
                "rawHtml": {
                    "description": "Raw HTML as received",
                    "type": "string"
                },
                "warning": {
                    "description": "Non-fatal warning",
                    "type": "string"
                }
            }
        },
        "github_com_MabudAlam_quickcrawl_internal_types.ScrapeRequest": {
            "type": "object",
            "properties": {
                "cssSelector": {
                    "description": "Extract specific element",
                    "type": "string"
                },
                "excludeTags": {
                    "description": "HTML tags to exclude",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "extract": {
                    "description": "LLM extraction options",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.ExtractOptions"
                        }
                    ]
                },
                "formats": {
                    "description": "Desired output formats",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.OutputFormat"
                    }
                },
                "headers": {
                    "description": "Custom HTTP headers",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "includeTags": {
                    "description": "HTML tags to include",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "jsonSchema": {
                    "description": "Schema for JSON output",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "llmExtractionPrompt": {
                    "description": "LLM extraction prompt override",
                    "type": "string"
                },
                "llmResponseFormat": {
                    "description": "LLM response format name override",
                    "type": "string"
                },
                "renderMode": {
                    "description": "Per-request override: \"auto\" | \"browser\" | \"http\". nil = inherit server default.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.RenderMode"
                        }
                    ]
                },
                "ttl": {
                    "description": "Cache TTL in seconds (0 = bypass cache, \u003e0 = accept cached if younger)",
                    "type": "integer"
                },
                "url": {
                    "description": "URL to scrape",
                    "type": "string"
                },
                "waitFor": {
                    "description": "Wait time in ms after page load",
                    "type": "integer"
                }
            }
        },
        "github_com_MabudAlam_quickcrawl_internal_types.SearchRequest": {
            "type": "object",
            "properties": {
                "categories": {
                    "description": "Comma-separated SearXNG categories, e.g. \"general,news\".",
                    "type": "string"
                },
                "formats": {
                    "description": "Desired output formats when scrape=true.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.OutputFormat"
                    }
                },
                "language": {
                    "description": "SearXNG language code, e.g. \"en\", \"auto\", \"all\".",
                    "type": "string"
                },
                "page": {
                    "description": "SearXNG pageno, default 1.",
                    "type": "integer"
                },
                "query": {
                    "description": "Search query (required)",
                    "type": "string"
                },
                "region": {
                    "description": "Region code, e.g. \"us-en\". Mapped to SearXNG language.",
                    "type": "string"
                },
                "renderMode": {
                    "description": "Per-request override: \"auto\" | \"browser\" | \"http\". nil = inherit server default.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.RenderMode"
                        }
                    ]
                },
                "scrape": {
                    "description": "Scrape each result URL and include extracted content (default: false).",
                    "type": "boolean"
                },
                "timeRange": {
                    "description": "SearXNG time range: \"day\", \"week\", \"month\", \"year\".",
                    "type": "string"
                },
                "use_bm25": {
                    "description": "Use BM25 scoring algorithm (default: false)",
                    "type": "boolean"
                }
            }
        },
        "github_com_MabudAlam_quickcrawl_internal_types.SearchResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "0-based page index.",
                    "type": "integer"
                },
                "query": {
                    "description": "Echo of the search query.",
                    "type": "string"
                },
                "results": {
                    "description": "List of search results.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_MabudAlam_quickcrawl_internal_types.SearchResult"
                    }
                },
                "total_results": {
                    "description": "Number of results returned.",
                    "type": "integer"
                }
            }
        },
        "github_com_MabudAlam_quickcrawl_internal_types.SearchResult": {
            "type": "object",
            "properties": {
                "bm25_score": {
                    "description": "BM25 relevance score (set when use_bm25=true)",
                    "type": "number"
                },
                "html": {
                    "type": "string"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "markdown": {
                    "type": "string"
                },
                "plain_text": {
                    "type": "string"
                },
                "position": {
                    "description": "1-based position in the result set",
                    "type": "integer"
                },
                "published_date": {
                    "description": "ISO 8601 publish date if available.",
                    "type": "string"
                },
                "raw_html": {
                    "type": "string"
                },
                "raw_json": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "score": {
                    "description": "Native score from search engine",
                    "type": "number"
                },
                "site_name": {
                    "description": "Hostname extracted from URL.",
                    "type": "string"
                },
                "snippet": {
                    "description": "Search snippet / description.",
                    "type": "string"
                },
                "title": {
                    "description": "Result title",
                    "type": "string"
                },
                "url": {
                    "description": "Result URL",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
