package core

import (
	"strings"
	"testing"
)

func TestNeedsJSRendering_DetectsSPAShell(t *testing.T) {
	html := `<html><head></head><body><div id="root"></div><script src="/app.js"></script></body></html>`
	if !needsJSRendering(html) {
		t.Error("expected needsJSRendering to return true for SPA shell with id=root")
	}
}

func TestNeedsJSRendering_StaticPageNoJSNeeded(t *testing.T) {
	html := `<html><body><article><h1>Hello World</h1><p>This is a long article with plenty of text content to read and enjoy. It has multiple paragraphs and lots of useful information.</p></article></body></html>`
	if needsJSRendering(html) {
		t.Error("expected needsJSRendering to return false for static page with rich content")
	}
}

func TestNeedsJSRendering_FrameworkMountPoints(t *testing.T) {
	cases := []struct {
		name string
		html string
		want bool
	}{
		{"id=root", `<html><body><div id="root"></div></body></html>`, true},
		{"id=__next", `<html><body><div id="__next"></div></body></html>`, true},
		{"id=__nuxt", `<html><body><div id="__nuxt"></div></body></html>`, true},
		{"id=__gatsby", `<html><body><div id="__gatsby"></div></body></html>`, true},
		{"data-reactroot", `<html><body><div data-reactroot="true"></div></body></html>`, true},
		{"data-sveltekit", `<html><body><div data-sveltekit="reload"></div></body></html>`, true},
		{"data-astro", `<html><body><div data-astro-mounted></div></body></html>`, true},
		{"ng-app", `<html><body ng-app></body></html>`, true},
		{"no body", `<html><head></head></html>`, false}, // bodyLen=1000 fallback, not < 200
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := needsJSRendering(c.html)
			if got != c.want {
				t.Errorf("needsJSRendering(%q) = %v, want %v", c.name, got, c.want)
			}
		})
	}
}

func TestLooksLikeGenericBotWall_PositiveCases(t *testing.T) {
	cases := []struct {
		name string
		html string
	}{
		{"cloudfront 403 block", `<html><head><title>ERROR: The request could not be satisfied</title></head>
            <body><h1>403 ERROR</h1>
            <h3>The request could not be satisfied.</h3>
            <p>The Amazon CloudFront distribution is configured to block access from your country.</p>
            <hr><i>Generated by cloudfront (CloudFront)</i></body></html>`},
		{"generic 403 block phrasing", `<html><body><h1>403</h1>
            <p>Our firewall is configured to block access from this region.</p></body></html>`},
		// QuickCrawl phrase: "verify you are human" (base verb, not "verifying")
		{"verify human", `<html><body><p>Please verify you are human to continue.</p></body></html>`},
		{"security check", `<html><body><p>Security check in progress.</p></body></html>`},
		{"access denied", `<html><body><p>Access denied.</p></body></html>`},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if !looksLikeGenericBotWall(c.html) {
				t.Errorf("looksLikeGenericBotWall(%q) = false, want true", c.name)
			}
		})
	}
}

func TestLooksLikeGenericBotWall_NegativeCases(t *testing.T) {
	// Long article about CloudFront must NOT trigger (600 char cap protects against this)
	html := `<html><body><article><h1>Why we use Cloudflare</h1>` +
		`<p>Performance benefits and DDoS protection. Cloudflare gives us global anycast network.</p>` +
		`</article></body></html>` + // enough text to exceed 600 char threshold
		strings.Repeat("<p> CloudFront distributions are configured to block access by country when needed.</p>", 20)
	if looksLikeGenericBotWall(html) {
		t.Error("expected looksLikeGenericBotWall to return false for long article about CloudFront")
	}
}

func TestLooksLikeGenericBotWall_LongPageNotTriggered(t *testing.T) {
	// Large pages are exempt (> 80k chars)
	html := strings.Repeat("<p>x</p>", 20000)
	if looksLikeGenericBotWall(html) {
		t.Error("expected looksLikeGenericBotWall to return false for huge page")
	}
}

func TestLooksLikeVendorBlock_Cloudflare(t *testing.T) {
	cases := []struct {
		name string
		html string
		want string
	}{
		{"challenge-form with token", `<html><body><form class="challenge-form" action="/?__cf_chl_f_tk=abc123"></form></body></html>`, "cloudflare"},
		{"cf-error-code", `<html><body><span class="cf-error-code">1020</span></body></html>`, "cloudflare"},
		{"challenge-platform", `<html><head><script src="/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=abc"></script></head></html>`, "cloudflare"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := looksLikeVendorBlock(c.html); got != c.want {
				t.Errorf("looksLikeVendorBlock(%q) = %q, want %q", c.name, got, c.want)
			}
		})
	}
}

func TestLooksLikeVendorBlock_Akamai(t *testing.T) {
	cases := []struct {
		name string
		html string
		want string
	}{
		{"pardon our interruption", `<html><body><h1>Pardon Our Interruption</h1>
            <p>As you were browsing, something about your browser made us think you were a bot.</p></body></html>`, "akamai"},
		{"reference ID", `<html><body><p>Access Denied</p>
            <p>Reference #18.2d351ab8.1557333295.a4e16ab</p></body></html>`, "akamai"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := looksLikeVendorBlock(c.html); got != c.want {
				t.Errorf("looksLikeVendorBlock(%q) = %q, want %q", c.name, got, c.want)
			}
		})
	}
}

func TestLooksLikeVendorBlock_PerimeterX(t *testing.T) {
	cases := []struct {
		name string
		html string
		want string
	}{
		{"pxAppId", `<html><head><script>window._pxAppId = 'PXabc123';</script></head></html>`, "perimeterx"},
		{"captcha px-cdn", `<html><body><iframe src="https://captcha.px-cdn.net/captcha/?initialCid=xyz"></iframe></body></html>`, "perimeterx"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := looksLikeVendorBlock(c.html); got != c.want {
				t.Errorf("looksLikeVendorBlock(%q) = %q, want %q", c.name, got, c.want)
			}
		})
	}
}

func TestLooksLikeVendorBlock_DataDome(t *testing.T) {
	html := `<html><body><iframe src="https://geo.captcha-delivery.com/captcha/?initialCid=xyz"></iframe></body></html>`
	if got := looksLikeVendorBlock(html); got != "datadome" {
		t.Errorf("looksLikeVendorBlock(datadome) = %q, want %q", got, "datadome")
	}
}

func TestLooksLikeVendorBlock_Imperva(t *testing.T) {
	html := `<html><body><script src="/_Incapsula_Resource?SWJIYLWA=blah"></script></body></html>`
	if got := looksLikeVendorBlock(html); got != "imperva" {
		t.Errorf("looksLikeVendorBlock(imperva) = %q, want %q", got, "imperva")
	}
}

func TestLooksLikeVendorBlock_Sucuri(t *testing.T) {
	html := `<html><body><h1>Sucuri WebSite Firewall - Access Denied</h1></body></html>`
	if got := looksLikeVendorBlock(html); got != "sucuri" {
		t.Errorf("looksLikeVendorBlock(sucuri) = %q, want %q", got, "sucuri")
	}
}

func TestLooksLikeVendorBlock_Kasada(t *testing.T) {
	html := `<html><body><script>kpsdk.scriptstart = kpsdk.now();</script></body></html>`
	if got := looksLikeVendorBlock(html); got != "kasada" {
		t.Errorf("looksLikeVendorBlock(kasada) = %q, want %q", got, "kasada")
	}
}

func TestLooksLikeVendorBlock_CloudFront(t *testing.T) {
	html := `<html><head><title>ERROR: The request could not be satisfied</title></head>
        <body><h1>403 ERROR</h1>
        <hr><i>Generated by cloudfront (CloudFront)</i></body></html>`
	if got := looksLikeVendorBlock(html); got != "cloudfront" {
		t.Errorf("looksLikeVendorBlock(cloudfront) = %q, want %q", got, "cloudfront")
	}
}

func TestLooksLikeVendorBlock_LegitBlogAboutCloudflare(t *testing.T) {
	// A 15KB+ legit page mentioning Cloudflare but with no challenge markers must NOT be flagged.
	html := "<html><body><article><h1>Why we picked Cloudflare</h1>" +
		strings.Repeat("<p>Cloudflare gives us DDoS protection and a global anycast network.</p>", 400) +
		"</article></body></html>"
	if got := looksLikeVendorBlock(html); got != "" {
		t.Errorf("looksLikeVendorBlock(legit blog) = %q, want empty string", got)
	}
}

func TestLooksLikeVendorBlock_OverSizePageReturnsEmpty(t *testing.T) {
	// Pages > 200KB return ""
	big := strings.Repeat("x", 300000)
	if got := looksLikeVendorBlock(big); got != "" {
		t.Errorf("looksLikeVendorBlock(oversized) = %q, want empty string", got)
	}
}

func TestLooksLikeVendorBlock_CleanPageReturnsEmpty(t *testing.T) {
	html := `<html><body><main><h1>Hello</h1><p>Real content.</p></main></body></html>`
	if got := looksLikeVendorBlock(html); got != "" {
		t.Errorf("looksLikeVendorBlock(clean page) = %q, want empty string", got)
	}
}

func TestLooksLikeCloudflareChallenge_StrongMarkers(t *testing.T) {
	cases := []struct {
		name string
		html string
		want bool
	}{
		{"cf-browser-verification", `<html><body><div id="cf-browser-verification">Just a moment...</div></body></html>`, true},
		{"window._cf_chl_opt", `<html><body><script>window._cf_chl_opt={cvId:'2'};</script></body></html>`, true},
		{"cdn-cgi challenge-platform", `<html><body><script src="/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=abc"></script></body></html>`, true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := looksLikeCloudflareChallenge(c.html); got != c.want {
				t.Errorf("looksLikeCloudflareChallenge(%q) = %v, want %v", c.name, got, c.want)
			}
		})
	}
}

func TestLooksLikeCloudflareChallenge_SingleWeakMarkerNotEnough(t *testing.T) {
	// A page that just mentions "Cloudflare" should not trigger
	html := `<html><body><article><h1>Why we use Cloudflare</h1><p>Performance benefits.</p></article></body></html>`
	if looksLikeCloudflareChallenge(html) {
		t.Error("expected looksLikeCloudflareChallenge to return false for page with only weak single marker")
	}
}

func TestLooksLikeCloudflareChallenge_TwoWeakMarkersTrigger(t *testing.T) {
	// Two challenge-specific phrases must co-occur.
	html := `<html><body><h1>Just a moment...</h1><p>Checking your browser...</p></body></html>`
	if !looksLikeCloudflareChallenge(html) {
		t.Error("expected looksLikeCloudflareChallenge to return true for page with 2+ weak markers")
	}
}

func TestLooksLikeCloudflareChallenge_RayIDAloneDoesNotTrigger(t *testing.T) {
	// "Ray ID" + "Cloudflare" both appear on benign CF-fronted pages — not enough alone
	html := `<html><body><h1>About</h1><p>Hosted via Cloudflare.</p><footer>Ray ID: abc123</footer></body></html>`
	if looksLikeCloudflareChallenge(html) {
		t.Error("expected looksLikeCloudflareChallenge to return false for page with only ray id")
	}
}

func TestLooksLikeCloudflareChallenge_HugePageNotScanned(t *testing.T) {
	// Pages > 80KB are exempt
	html := strings.Repeat("<p>x</p>", 20000)
	if looksLikeCloudflareChallenge(html) {
		t.Error("expected looksLikeCloudflareChallenge to return false for huge page")
	}
}

func TestIsSoftBlockStatus(t *testing.T) {
	codes := []struct {
		code    uint16
		isBlock bool
	}{
		{200, false}, {301, false}, {401, true}, {403, true}, {404, true},
		{405, true}, {406, true}, {410, true}, {412, true}, {429, true},
		{451, true}, {500, true}, {503, true}, {502, false}, {200, false},
	}
	for _, c := range codes {
		t.Run("", func(t *testing.T) {
			if got := isSoftBlockStatus(c.code); got != c.isBlock {
				t.Errorf("isSoftBlockStatus(%d) = %v, want %v", c.code, got, c.isBlock)
			}
		})
	}
}

func TestIsPDFContentType(t *testing.T) {
	cases := []string{"application/pdf", "application/pdf", "text/html", "text/plain", ""}
	want := []bool{true, true, false, false, false}
	for i, ct := range cases {
		if got := isPDFContentType(ct); got != want[i] {
			t.Errorf("isPDFContentType(%q) = %v, want %v", ct, got, want[i])
		}
	}
}

func TestLooksLikeThinHTML(t *testing.T) {
	cases := []struct {
		name string
		html string
		want bool
	}{
		{"empty body", `<html><body></body></html>`, true},
		{"tiny text", `<html><body><p>Hi</p></body></html>`, true},
		// QuickCrawl's static_page_no_js_needed test — body text > 200 chars
		{"rich content", `<html><body><article><h1>Hello World</h1><p>This is a long article with plenty of text content to read and enjoy. It has multiple paragraphs and lots of useful information.</p><p>Additional paragraph to exceed the 200-char body text threshold so thin HTML detection does not trigger.</p></article></body></html>`, false},
		{"no body tag", `<html><head></head>`, false}, // returns 1000 fallback
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := looksLikeThinHTML(c.html); got != c.want {
				t.Errorf("looksLikeThinHTML(%q) = %v, want %v", c.name, got, c.want)
			}
		})
	}
}

func TestExtractBodyTextLen(t *testing.T) {
	cases := []struct {
		name string
		html string
		want int
	}{
		{"no body tag", `<html><head></head>`, 1000},
		{"empty body", `<html><body></body></html>`, 0},
		{"rich article", `<html><body><article><h1>Hello World</h1><p>This is a long article with plenty of text content.</p></article></body></html>`, 62},
		{"script stripped", `<html><body><script>var x=1;</script><p>Real content here</p></body></html>`, 17},
		{"style stripped", `<html><body><style>body{}</style><p>Text</p></body></html>`, 4},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := extractBodyTextLen(strings.ToLower(c.html)); got != c.want {
				t.Errorf("extractBodyTextLen(%q) = %d, want %d", c.name, got, c.want)
			}
		})
	}
}

func TestStripTagBlocks(t *testing.T) {
	html := `<html><body><script>var x=1;</script><p>Hello</p><style>body{}</style><div>World</div></body></html>`
	scriptRemoved := stripTagBlocks(strings.ToLower(html), "script")
	scriptAndStyleRemoved := stripTagBlocks(scriptRemoved, "style")
	if scriptRemoved == html {
		t.Error("stripTagBlocks should have removed script tag")
	}
	if scriptAndStyleRemoved == scriptRemoved {
		t.Error("stripTagBlocks should have removed style tag")
	}
	if !strings.Contains(scriptAndStyleRemoved, "<p>hello</p>") {
		t.Error("paragraph should remain after stripping script and style")
	}
}

func TestBodyHTMLWithoutScriptsLower(t *testing.T) {
	html := `<html><head><script>var x=1;</script></head><body><p>Content</p><style>body{}</style></body></html>`
	body := bodyHTMLWithoutScriptsLower(strings.ToLower(html))
	if body == "" {
		t.Error("bodyHTMLWithoutScriptsLower should not return empty string for valid HTML")
	}
	if strings.Contains(body, "<script>") {
		t.Error("body should not contain script tags")
	}
	if strings.Contains(body, "<style>") {
		t.Error("body should not contain style tags")
	}
}

func TestVisibleTextFromStrippedHTML(t *testing.T) {
	html := `<html><body><script>x</script><p>Hello   World</p> <div>Test</div></body></html>`
	stripped := bodyHTMLWithoutScriptsLower(strings.ToLower(html))
	text := visibleTextFromStrippedHTML(stripped)
	// Space between </p> and <div> in the source creates word boundary between "world" and "test"
	if text != "hello world test" {
		t.Errorf("visibleTextFromStrippedHTML got %q, want %q", text, "hello world test")
	}
}

func TestNeedsJSRendering_NoScriptWithJSWarning(t *testing.T) {
	html := `<html><body><noscript>Please enable JavaScript</noscript></body></html>`
	if !needsJSRendering(html) {
		t.Error("expected needsJSRendering to return true for noscript with enable javascript")
	}
}

func TestNeedsJSRendering_BuilderPlatforms(t *testing.T) {
	cases := []struct {
		name string
		html string
		want bool
	}{
		{"framerusercontent", `<html><body><p>Content from https://framerusercontent.com/assets/123</p></body></html>`, true},
		{"webflow", `<html><body><p>Site hosted at webflow.io/some-site</p></body></html>`, true},
		{"wixsite", `<html><body><p>My site is on wixsite.com</p></body></html>`, true},
		{"squarespace universal", `<html><body><p>Delivered via squarespace.com/universal</p></body></html>`, true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := needsJSRendering(c.html); got != c.want {
				t.Errorf("needsJSRendering(%q) = %v, want %v", c.name, got, c.want)
			}
		})
	}
}

func TestNeedsJSRendering_ManyScripts(t *testing.T) {
	// Short body + 5+ <script tags → needs JS
	html := `<html><body><script src="a"></script><script src="b"></script><script src="c"></script><script src="d"></script><script src="e"></script></body></html>`
	if !needsJSRendering(html) {
		t.Error("expected needsJSRendering to return true for short body with 5+ script tags")
	}
}

func TestNeedsJSRendering_Storybook(t *testing.T) {
	html := `<html><body><div id="storybook-root"></div></body></html>`
	if !needsJSRendering(html) {
		t.Error("expected needsJSRendering to return true for Storybook indicator")
	}
}

func TestEscalationReason_SpaShell(t *testing.T) {
	html := `<html><head></head><body><div id="root"></div><script src="/app.js"></script></body></html>`
	if got := escalationReason(html, 200); got != "SPA shell detected" {
		t.Errorf("escalationReason = %q, want %q", got, "SPA shell detected")
	}
}

func TestEscalationReason_SoftBlockStatus(t *testing.T) {
	html := `<html><body><p>` + strings.Repeat("real content here. ", 30) + `</p></body></html>`
	if got := escalationReason(html, 403); got != "soft-block status HTTP 403" {
		t.Errorf("escalationReason = %q, want %q", got, "soft-block status HTTP 403")
	}
}

func TestEscalationReason_ThinContent(t *testing.T) {
	html := `<html><body></body></html>`
	if got := escalationReason(html, 200); got != "thin HTML content" {
		t.Errorf("escalationReason = %q, want %q", got, "thin HTML content")
	}
}

func TestEscalationReason_CloudflareChallenge(t *testing.T) {
	html := `<html><body><title>Just a moment...</title><div>Checking your browser before accessing. ` + strings.Repeat("verifying you are human, please stand by. ", 15) + `</div></body></html>`
	if got := escalationReason(html, 200); got != "Cloudflare challenge detected" {
		t.Errorf("escalationReason = %q, want %q", got, "Cloudflare challenge detected")
	}
}

func TestEscalationReason_NoEscalation(t *testing.T) {
	html := `<html><body><article><p>` + strings.Repeat("lorem ipsum dolor sit amet consectetur. ", 20) + `</p></article></body></html>`
	if got := escalationReason(html, 200); got != "" {
		t.Errorf("escalationReason = %q, want %q", got, "")
	}
}

func TestEscalationReason_OrderingSpaWinsOverThin(t *testing.T) {
	// An SPA shell (empty body) must report SPA before the thin-content trigger.
	html := `<html><body><div id="app"></div></body></html>`
	if got := escalationReason(html, 200); got != "SPA shell detected" {
		t.Errorf("escalationReason = %q, want %q", got, "SPA shell detected")
	}
}
