package core

import (
	"fmt"
	"regexp"
	"strings"
)

var akamaiRefRe = regexp.MustCompile(`Reference #\d+\.[0-9a-f]+\.\d+\.[0-9a-f]+`)

// needsJSRendering returns true when the HTML looks like an SPA shell that needs
// JS rendering. Mirrors QuickCrawl's detector::needs_js_rendering.
func needsJSRendering(html string) bool {
	checkLen := len(html)
	if checkLen > 500_000 {
		checkLen = 500_000
	}
	lower := strings.ToLower(html[:checkLen])

	bodyLen := extractBodyTextLen(lower)

	// Very short body text + presence of JS framework indicators.
	if bodyLen < 200 {
		spaIndicators := []string{
			`id="root"`, `id="app"`, `id="__next"`, `id="__nuxt"`, `id="__gatsby"`, `id="svelte"`,
			"ng-app", "data-reactroot", "data-reactid", "data-remix-run", "data-sveltekit",
			"data-astro-", "<script src", "window.__initial_state__", "__next_data__",
			"__nuxt__", "__sveltekit_data", "window.__remixcontext", "window.__astro",
			"gatsby-focus-wrapper",
		}
		for _, ind := range spaIndicators {
			if strings.Contains(lower, ind) {
				return true
			}
		}
	}

	// Noscript tag with meaningful content suggests JS is needed.
	if strings.Contains(lower, "<noscript>") && strings.Contains(lower, "enable javascript") {
		return true
	}

	// Builder/platform markers (often fully JS-rendered).
	if bodyLen < 500 {
		builderIndicators := []string{
			"framerusercontent.com", "webflow.io", "wixsite.com", "squarespace.com/universal",
		}
		for _, ind := range builderIndicators {
			if strings.Contains(lower, ind) {
				return true
			}
		}
	}

	// Bundler-heavy modern SPA: short body + many script tags.
	if bodyLen < 1000 {
		scriptCount := strings.Count(lower, "<script")
		if scriptCount >= 5 {
			return true
		}
		storybookIndicators := []string{
			`id="storybook-root"`, `id="storybook-docs"`, "__storybook", "?path=/docs/", "/iframe.html",
		}
		for _, ind := range storybookIndicators {
			if strings.Contains(lower, ind) {
				return true
			}
		}
	}

	return false
}

// looksLikeGenericBotWall returns true for generic anti-bot interstitials.
// Uses visible body text (scripts/styles stripped) so JS bundle content doesn't
// false-positive. Only triggers on pages with visible body text <= 600 chars.
// Mirrors QuickCrawl's detector::looks_like_generic_bot_wall.
func looksLikeGenericBotWall(html string) bool {
	if len(html) > 80_000 {
		return false
	}
	lower := strings.ToLower(html)
	bodyStripped := bodyHTMLWithoutScriptsLower(lower)
	bodyText := visibleTextFromStrippedHTML(bodyStripped)
	if len(bodyText) > 600 {
		return false
	}

	phrases := []string{
		"performing security verification",
		"verify you are human",
		"checking your browser",
		"enable javascript and cookies",
		"security check",
		"access denied",
		"request blocked",
		"the request could not be satisfied",
		"generated by cloudfront",
		"configured to block access",
	}
	for _, p := range phrases {
		if strings.Contains(bodyText, p) {
			return true
		}
	}
	return false
}

// looksLikeVendorBlock returns the matched vendor name or "". Scans first 15KB
// of HTML (vendor block pages are small). Returns for pages > 200KB.
// Vendors: cloudflare, akamai, perimeterx, datadome, imperva, sucuri, kasada, cloudfront.
// Mirrors QuickCrawl's detector::looks_like_vendor_block.
func looksLikeVendorBlock(html string) string {
	if len(html) > 200_000 {
		return ""
	}
	headLen := len(html)
	if headLen > 15_000 {
		headLen = 15_000
	}
	head := html[:headLen]
	lowerHead := strings.ToLower(head)

	// Cloudflare: challenge form with cf-managed token, or cf-error-code span,
	// or challenge-platform JS loader.
	if (strings.Contains(lowerHead, "challenge-form") && strings.Contains(lowerHead, "__cf_chl_f_tk=")) ||
		strings.Contains(lowerHead, "cf-error-code") ||
		strings.Contains(lowerHead, "/cdn-cgi/challenge-platform/") {
		return "cloudflare"
	}

	// Akamai: "Pardon Our Interruption" or Reference #<hex>.<hex>.<hex>.<hex>.
	if strings.Contains(lowerHead, "pardon our interruption") || akamaiRefRe.MatchString(head) {
		return "akamai"
	}

	// PerimeterX: window._pxAppId SDK assignment, or owned captcha CDN.
	if strings.Contains(lowerHead, "window._pxappid =") || strings.Contains(lowerHead, "captcha.px-cdn.net") {
		return "perimeterx"
	}

	// DataDome: owned captcha delivery domain.
	if strings.Contains(lowerHead, "captcha-delivery.com") {
		return "datadome"
	}

	// Imperva/Incapsula: resource marker + incident ID phrasing.
	if strings.Contains(lowerHead, "_incapsula_resource") || strings.Contains(lowerHead, "incapsula incident id") {
		return "imperva"
	}

	// Sucuri: WAF block page brand string.
	if strings.Contains(lowerHead, "sucuri website firewall") {
		return "sucuri"
	}

	// Kasada: SDK signature.
	if strings.Contains(lowerHead, "kpsdk.scriptstart = kpsdk.now()") {
		return "kasada"
	}

	// CloudFront/AWS WAF.
	if strings.Contains(lowerHead, "generated by cloudfront") || strings.Contains(lowerHead, "the request could not be satisfied") {
		return "cloudfront"
	}

	return ""
}

// looksLikeCloudflareChallenge returns true for Cloudflare anti-bot challenge/interstitial.
// Uses two-tier logic: any strong marker triggers immediately, OR 2+ weak markers co-occur.
// Weak markers alone are not enough — most marketing pages reference Cloudflare somewhere.
// Scans first 80KB only. Mirrors QuickCrawl's detector::looks_like_cloudflare_challenge.
func looksLikeCloudflareChallenge(html string) bool {
	if len(html) > 80_000 {
		return false
	}
	lower := strings.ToLower(html)

	// Strong markers: appear ONLY on the Cloudflare interstitial.
	strong := []string{
		"cf-browser-verification",
		"cf-challenge-running",
		"/cdn-cgi/challenge-platform/",
		"_cf_chl_opt",
		"window._cf_chl_opt",
	}
	for _, m := range strong {
		if strings.Contains(lower, m) {
			return true
		}
	}

	// Weak markers: each can appear on legitimate Cloudflare-fronted pages.
	// Require 2+ co-occurring to trigger (challenge-specific phrasing).
	weak := []string{
		"just a moment",
		"checking your browser",
		"attention required",
		"performance &amp; security by cloudflare",
		"performance & security by cloudflare",
	}
	hits := 0
	for _, m := range weak {
		if strings.Contains(lower, m) {
			hits++
		}
	}
	return hits >= 2
}

// looksLikeThinHTML returns true when an HTTP response yielded effectively no visible
// body text (< 200 chars after script/style strip). Used to decide whether to escalate
// a "successful" HTTP fetch to JS rendering. Mirrors QuickCrawl's detector::looks_like_thin_html.
func looksLikeThinHTML(html string) bool {
	checkLen := len(html)
	if checkLen > 500_000 {
		checkLen = 500_000
	}
	lower := html[:checkLen]
	return extractBodyTextLen(lower) < 200
}

// isSoftBlockStatus returns true for soft-block HTTP status codes that typically
// indicate a challenge or block page rather than genuinely missing content.
// Used to escalate to JS renderer. Mirrors QuickCrawl's soft-block status detection.
func isSoftBlockStatus(statusCode uint16) bool {
	switch statusCode {
	case 401, 403, 404, 405, 406, 410, 412, 429, 451, 500, 503:
		return true
	}
	return false
}

// isPDFContentType returns true for PDF content type.
func isPDFContentType(ct string) bool {
	return ct == "application/pdf"
}

// isAntiBotPage checks page HTML for generic anti-bot challenge markers.
// This includes Cloudflare "Just a Moment" pages, CAPTCHA pages, and generic
// access denied messages. It is a simple string search and does not detect
// vendor-specific blocks (Akamai, PerimeterX, Datadome, etc. are only in
// the original renderer).
//
// The marker set is intentionally broad — false positives are cheap (a
// block page is returned with a warning instead of waiting 15s for the
// SPA poll to time out and 3s for autoscroll to give up). Real content
// pages very rarely contain these substrings in their first 1KB of
// body text.
func isAntiBotPage(html string) bool {
	html = strings.ToLower(html)
	markers := []string{
		// Cloudflare variants — covers "Just a Moment" challenges,
		// generic blocks, and the per-incident "Ray ID" error pages.
		"just a moment",
		"attention required",
		"cf-browser-verification",
		"cf-challenge",
		"checking your browser before accessing",
		"this site is using a security service to protect itself",
		"ray id",                      // Cloudflare incident id on error pages
		"cloudflare",                  // generic CF identifier
		"blocked by network security", // Reddit's Cloudflare-block text
		"your request has been blocked",
		// Generic / vendor-agnostic. We intentionally omit the
		// very common word "forbidden" — it false-positives on
		// book titles and code comments, and 403 status codes
		// already cover the legitimate-block case at the HTTP
		// level. "captcha" is kept because it is a strong
		// anti-bot signal and rarely appears in regular content.
		"captcha",
		"access denied",
	}
	for _, m := range markers {
		if strings.Contains(html, m) {
			return true
		}
	}
	return false
}

// escalationReason is the preflight check for deciding whether an HTTP-fetched
// page must be re-fetched in a real browser (JS rendering). It returns a human
// reason when escalation is warranted, or "" when the HTTP result is fine as-is.
// The first matching trigger wins; ordering and status gating mirror the
// original auto-mode logic (soft-block applies on any status, thin-content and
// anti-bot detection only on 2xx).
func escalationReason(html string, statusCode uint16) string {
	if needsJSRendering(html) {
		return "SPA shell detected"
	}
	if isSoftBlockStatus(statusCode) {
		return fmt.Sprintf("soft-block status HTTP %d", statusCode)
	}
	if statusCode >= 200 && statusCode < 300 {
		if looksLikeThinHTML(html) {
			return "thin HTML content"
		}
		if looksLikeCloudflareChallenge(html) {
			return "Cloudflare challenge detected"
		}
		if looksLikeGenericBotWall(html) {
			return "generic anti-bot wall detected"
		}
		if vendor := looksLikeVendorBlock(html); vendor != "" {
			return "anti-bot vendor block: " + vendor
		}
	}
	return ""
}

// bodyHTMLWithoutScriptsLower returns the <body> content of a lowercased HTML doc
// with <script> and <style> blocks stripped. Returns "" if no <body> found.
func bodyHTMLWithoutScriptsLower(lower string) string {
	bodyStart := strings.Index(lower, "<body")
	if bodyStart == -1 {
		return ""
	}
	afterBody := bodyStart + len("<body")
	openIdx := strings.Index(lower[afterBody:], ">")
	if openIdx == -1 {
		return ""
	}
	bodyStartIdx := afterBody + openIdx + 1
	bodyEndIdx := strings.LastIndex(lower, "</body>")
	if bodyEndIdx == -1 || bodyEndIdx <= bodyStartIdx {
		return ""
	}

	body := lower[bodyStartIdx:bodyEndIdx]
	body = stripTagBlocks(body, "script")
	body = stripTagBlocks(body, "style")
	return body
}

// visibleTextFromStrippedHTML strips all HTML tags from already-script/style-stripped
// HTML and returns the visible text. Whitespace is collapsed.
func visibleTextFromStrippedHTML(stripped string) string {
	var text strings.Builder
	text.Grow(len(stripped))
	inTag := false
	prevWS := false
	for _, ch := range stripped {
		if ch == '<' {
			inTag = true
		} else if ch == '>' {
			inTag = false
		} else if !inTag {
			if ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r' {
				if !prevWS {
					text.WriteByte(' ')
					prevWS = true
				}
			} else {
				text.WriteRune(ch)
				prevWS = false
			}
		}
	}
	return text.String()
}

// extractBodyTextLen returns non-whitespace character count inside <body> of a
// lowercased HTML doc. Returns 1000 ("probably has content") if no <body> found.
func extractBodyTextLen(lower string) int {
	bodyStart := strings.Index(lower, "<body")
	if bodyStart == -1 {
		return 1000
	}
	afterBody := bodyStart + len("<body")
	openIdx := strings.Index(lower[afterBody:], ">")
	if openIdx == -1 {
		return 0
	}
	bodyStartIdx := afterBody + openIdx + 1
	bodyEndIdx := strings.LastIndex(lower, "</body>")
	if bodyEndIdx == -1 || bodyEndIdx <= bodyStartIdx {
		return 0
	}
	body := lower[bodyStartIdx:bodyEndIdx]
	body = stripTagBlocks(body, "script")
	body = stripTagBlocks(body, "style")
	return len(visibleTextFromStrippedHTML(body))
}

// stripTagBlocks removes all <tag...>...</tag> blocks from HTML. Input is assumed
// to be already lowercased. Mirrors QuickCrawl's strip_tag_blocks.
func stripTagBlocks(html string, tag string) string {
	result := strings.Builder{}
	result.Grow(len(html))
	open := "<" + tag
	close := "</" + tag + ">"
	remaining := html

	for {
		idx := strings.Index(remaining, open)
		if idx == -1 {
			result.WriteString(remaining)
			break
		}
		result.WriteString(remaining[:idx])
		afterOpen := remaining[idx:]
		closeIdx := strings.Index(afterOpen, close)
		if closeIdx == -1 {
			break
		}
		remaining = afterOpen[closeIdx+len(close):]
	}
	return result.String()
}
