package utils

import (
	"regexp"
	"strings"
)

var akamaiRefPattern = regexp.MustCompile(`Reference #\d+\.[0-9a-f]+\.\d+\.[0-9a-f]+`)

func PageNeedsJavaScript(html string) bool {
	if len(html) > 500000 {
		return false
	}

	checkLen := len(html)
	if checkLen > 500000 {
		checkLen = 500000
	}
	lower := strings.ToLower(html[:checkLen])
	bodyLen := ExtractBodyTextLength(lower)

	if bodyLen < 200 {
		spaIndicators := []string{
			`id="root"`,
			`id="app"`,
			`id="__next"`,
			`id="__nuxt"`,
			`id="__gatsby"`,
			`id="svelte"`,
			`ng-app`,
			`data-reactroot`,
			`data-reactid`,
			`data-remix-run`,
			`data-sveltekit`,
			`data-astro-`,
			`<script src`,
			"window.__initial_state__",
			"__next_data__",
			"__nuxt__",
			"__sveltekit_data",
			"window.__remixcontext",
			"window.__astro",
			"gatsby-focus-wrapper",
		}
		for _, indicator := range spaIndicators {
			if strings.Contains(lower, indicator) {
				return true
			}
		}
	}

	if strings.Contains(lower, "<noscript>") && strings.Contains(lower, "enable javascript") {
		return true
	}

	if bodyLen < 500 {
		builderIndicators := []string{
			"framerusercontent.com",
			"webflow.io",
			"wixsite.com",
			"squarespace.com/universal",
		}
		for _, indicator := range builderIndicators {
			if strings.Contains(lower, indicator) {
				return true
			}
		}
	}

	if bodyLen < 1000 {
		if strings.Count(lower, "<script") >= 5 {
			return true
		}

		storybookIndicators := []string{
			`id="storybook-root"`,
			`id="storybook-docs"`,
			"__storybook",
			"?path=/docs/",
			"/iframe.html",
		}
		for _, indicator := range storybookIndicators {
			if strings.Contains(lower, indicator) {
				return true
			}
		}
	}

	return false
}

func PageLooksLikeGenericBotWall(html string) bool {
	if len(html) > 80000 {
		return false
	}

	lower := strings.ToLower(html)
	bodyStripped := bodyHTMLWithoutScriptsLower(lower)
	bodyText := VisibleTextFromStrippedHTML(bodyStripped)
	if countVisibleRunes(bodyText) > 600 {
		return false
	}

	phrases := []string{
		"performing security verification",
		"verify you are human",
		"checking your browser",
		"enable javascript and cookies",
		"security check",
		"access denied",
		"request blocked",
		"the request could not be satisfied",
		"generated by cloudfront",
		"configured to block access",
	}
	for _, phrase := range phrases {
		if strings.Contains(bodyText, phrase) {
			return true
		}
	}

	return false
}

func PageLooksLikeVendorBlock(html string) string {
	if len(html) > 200000 {
		return ""
	}

	head := html
	if len(head) > 15000 {
		head = head[:15000]
	}
	lowerHead := strings.ToLower(head)

	if (strings.Contains(lowerHead, "challenge-form") && strings.Contains(lowerHead, "__cf_chl_f_tk=")) ||
		strings.Contains(lowerHead, "cf-error-code") ||
		strings.Contains(lowerHead, "/cdn-cgi/challenge-platform/") {
		return "cloudflare"
	}
	if strings.Contains(lowerHead, "pardon our interruption") || akamaiRefPattern.MatchString(head) {
		return "akamai"
	}
	if strings.Contains(lowerHead, "window._pxappid =") || strings.Contains(lowerHead, "captcha.px-cdn.net") {
		return "perimeterx"
	}
	if strings.Contains(lowerHead, "captcha-delivery.com") {
		return "datadome"
	}
	if strings.Contains(lowerHead, "_incapsula_resource") || strings.Contains(lowerHead, "incapsula incident id") {
		return "imperva"
	}
	if strings.Contains(lowerHead, "sucuri website firewall") {
		return "sucuri"
	}
	if strings.Contains(lowerHead, "kpsdk.scriptstart = kpsdk.now()") {
		return "kasada"
	}
	if strings.Contains(lowerHead, "generated by cloudfront") ||
		strings.Contains(lowerHead, "the request could not be satisfied") {
		return "cloudfront"
	}

	return ""
}

func PageLooksLikeThinHTML(html string) bool {
	if len(html) > 500000 {
		return false
	}
	checkLen := len(html)
	if checkLen > 500000 {
		checkLen = 500000
	}
	lower := strings.ToLower(html[:checkLen])
	return ExtractBodyTextLength(lower) < 200
}

type FailedRenderReason string

const (
	FailedRenderNextJsClientError  FailedRenderReason = "nextjs_client_error"
	FailedRenderReactMinifiedError FailedRenderReason = "react_minified_error"
	FailedRenderEmptyNextRoot      FailedRenderReason = "empty_next_root"
)

func PageLooksLikeFailedRender(html string) (FailedRenderReason, bool) {
	if len(html) > 200000 {
		return "", false
	}

	lower := strings.ToLower(html)
	if strings.Contains(lower, `id="__next-error-`) || strings.Contains(lower, "data-nextjs-error") {
		return FailedRenderNextJsClientError, true
	}
	if strings.Contains(lower, `id="__next_error__"`) {
		return FailedRenderNextJsClientError, true
	}
	if strings.Contains(lower, "https://react.dev/errors/") || strings.Contains(lower, "https://reactjs.org/docs/error-decoder") {
		return FailedRenderReactMinifiedError, true
	}

	if start := strings.Index(lower, `id="__next"`); start != -1 {
		afterID := lower[start:]
		if close := strings.Index(afterID, ">"); close != -1 {
			tail := afterID[close+1:]
			if end := strings.Index(tail, "</div>"); end != -1 {
				if strings.TrimSpace(tail[:end]) == "" {
					return FailedRenderEmptyNextRoot, true
				}
			}
		}
	}

	return "", false
}

func PageLooksLikeLoadingPlaceholder(html string) bool {
	if len(html) > 80000 {
		return false
	}

	lower := strings.ToLower(html)
	bodyStripped := bodyHTMLWithoutScriptsLower(lower)
	bodyText := VisibleTextFromStrippedHTML(bodyStripped)
	bodyTextLen := countVisibleRunes(bodyText)

	if bodyTextLen == 0 {
		return true
	}

	if bodyTextLen < 400 {
		loadingMarkers := []string{
			"loading...",
			"loading…",
			"please wait",
			"just a moment",
			"initializing",
			"preparing",
			"one moment",
		}
		for _, marker := range loadingMarkers {
			if strings.Contains(bodyText, marker) {
				return true
			}
		}
	}

	if bodyTextLen < 200 {
		spinnerMarkers := []string{
			`class="spinner`,
			`class="loader`,
			`class="loading`,
			`class="preloader`,
			`id="loader`,
			`id="preloader`,
			`aria-label="loading"`,
		}
		for _, marker := range spinnerMarkers {
			if strings.Contains(bodyStripped, marker) {
				return true
			}
		}
	}

	return false
}

func PageHasBlockInterstitial(html string) bool {
	if len(html) > 500000 {
		return false
	}

	lower := strings.ToLower(html)
	markers := []string{
		"just a moment",
		"attention required",
		"cf-browser-verification",
		"cf-challenge",
		"captcha",
		"access denied",
	}
	for _, marker := range markers {
		if strings.Contains(lower, marker) {
			return true
		}
	}

	return PageLooksLikeGenericBotWall(html) || PageLooksLikeVendorBlock(html) != ""
}

func PageHasClientSideCrash(html string) bool {
	if _, ok := PageLooksLikeFailedRender(html); ok {
		return true
	}

	lower := strings.ToLower(html)
	markers := []string{
		"application error: a client-side exception has occurred",
		"client-side exception has occurred",
		"application error",
		"something went wrong",
		"unexpected application error",
		"uncaught exception",
	}
	for _, marker := range markers {
		if strings.Contains(lower, marker) {
			return true
		}
	}
	return false
}

func PageHasMinimalContent(html string) bool {
	return PageLooksLikeThinHTML(html)
}

func VisibleTextLength(html string) int {
	return ExtractBodyTextLength(strings.ToLower(html))
}

func CopyHeaders(headers map[string]string) map[string]string {
	if len(headers) == 0 {
		return map[string]string{}
	}
	out := make(map[string]string, len(headers))
	for k, v := range headers {
		out[k] = v
	}
	return out
}

func bodyHTMLWithoutScriptsLower(lower string) string {
	bodyStart := strings.Index(lower, "<body")
	if bodyStart == -1 {
		return ""
	}
	afterOpen := strings.Index(lower[bodyStart:], ">")
	if afterOpen == -1 {
		return ""
	}
	bodyStart += afterOpen + 1
	bodyEnd := strings.LastIndex(lower, "</body>")
	if bodyEnd == -1 || bodyStart >= bodyEnd {
		return ""
	}

	body := lower[bodyStart:bodyEnd]
	body = stripTagBlocks(body, "script")
	return stripTagBlocks(body, "style")
}

func VisibleTextFromStrippedHTML(stripped string) string {
	var builder strings.Builder
	builder.Grow(len(stripped))
	inTag := false
	prevSpace := true
	for _, ch := range stripped {
		switch ch {
		case '<':
			inTag = true
		case '>':
			inTag = false
		default:
			if inTag {
				continue
			}
			if strings.ContainsRune(" \t\r\n", ch) {
				if !prevSpace {
					builder.WriteByte(' ')
					prevSpace = true
				}
				continue
			}
			builder.WriteRune(ch)
			prevSpace = false
		}
	}
	return builder.String()
}

func ExtractBodyTextLength(lower string) int {
	if !strings.Contains(lower, "<body") {
		return 1000
	}
	stripped := bodyHTMLWithoutScriptsLower(lower)
	return countVisibleRunes(VisibleTextFromStrippedHTML(stripped))
}

func stripTagBlocks(html, tag string) string {
	var result strings.Builder
	result.Grow(len(html))
	open := "<" + tag
	closeTag := "</" + tag + ">"
	remaining := html

	for {
		start := strings.Index(remaining, open)
		if start == -1 {
			result.WriteString(remaining)
			break
		}
		result.WriteString(remaining[:start])
		afterOpen := remaining[start:]
		end := strings.Index(afterOpen, closeTag)
		if end == -1 {
			break
		}
		remaining = afterOpen[end+len(closeTag):]
	}

	return result.String()
}

func countVisibleRunes(text string) int {
	count := 0
	for _, ch := range text {
		if !strings.ContainsRune(" \t\r\n", ch) {
			count++
		}
	}
	return count
}
